apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: csccm
  labels:
    app: csccm
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: csccm
    spec:
      serviceAccountName: cloud-controller-manager
      containers:
        - image: IMAGE
          imagePullPolicy: Always
          name: csccm
          command: ["./csccm"]
          args:
          - --cloud-config
          - /etc/kubernetes/cloud-config
          - --v=4
          volumeMounts:
          - mountPath: /etc/kubernetes
            name: k8s
          ports:
            - containerPort: 9844
              name: web
              protocol: TCP
      volumes:
      - name: k8s
        hostPath:
          path: /etc/kubernetes/