language: go
install: true
sudo: required
addons:
  apt:
    packages:
    - docker-ce
go:
- 1.13.x
jobs:
  fast_finish: true
  include:
  - script: make test
  - script: make lint
  - stage: push to docker
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - if [ -n "$TRAVIS_TAG" ]; then make TAG=$TRAVIS_TAG push; else make push; fi
    if: "(NOT type IN (pull_request)) AND (branch = master) OR (tag IS present)"
env:
  global:
  - secure: "TpqAxagi+7NFBedE3gl5p1qK56DP8nWPPHixbiaa7arPpUuiHTmUenaVUXQ7CMUQOlTbU7U3DETDHaGbMQh7WQngol0m92sdO1z3uwtC44Jk8cfW5fSbfGZsTMyWSBTASppxweP9+cO8Vjbcg4FuP92DuDjrjX/ucZoEVNQ27F6GQZ/geEsxS+rOIxhPiASpDX/Q1o3lEtoZQ38YNwXe14nJZVmI4kwMdHZQCliB8+Rc7fK6/0/QJeX3pzbeqHGTCk1EcMnthRvxBDGqwZ3f6o1Uj4DwUemPVpHckndbxYz+xMOO3E2jMDjg9HNHQ38ywZHr8tHk+pZqsvrg2wRAMxUTU2TOwlOh7RXc7oBmT5VtjompDRizTN1NBileyhQBM9LV6Hf/2zCXz92m7t+riM9Kj+ThBmzcoTNJtIivshJn9a66zOL4ON6hdvFPVaxTIuqzlj2vPBwt2OBBruATbkgv2kbdyvUyvBDsIo1mdeXrLD/4HddBdkJYxTCQZQ7fpq88AdEH3LAChOgVj2VJP6hDfME2HKhkD0B7I037QZ9K+VsyCvk81V6JqJRMcWxb/dO7/2cTs8zlqQB0aKdd3IFDir3rE45LcL7Dxh/HreTI/q9MNSfLCAqyJC/LUiSUahMtdGWKUeeXRUVIs2c4N8zV2GKherMfx42KKzng2F0="
  - secure: "bGE3s+tgxWLUlksuLPoREL9asrqejSpmAvdM0DEsD1/Pt0T9PRLXXdQwNiTmqUSJ0MNMNBsHI6gef73XmieKsnFPxzpucVnjB1nHzHfD71Ssm8lOnkwJKF+j4e3r1rkJ2eP5w8TcXg2W8pScbaw0d97Atp1A/4CApOCQpVDll6IiULRgbPtOlscNgntr1PVtToY2CgC3EEIPWWBvqlIjhA6BZEI2HxY9ou/7iH9JbvY9YG2HZR+fBU8BdFaVSm/5vWnFH1MT49JzBqMhejkJQQW1DL3NoJTr6Bzjo4vc8aPZzD2pGekM1lf84zm+c0Q74DGyGgUNqV3QTk/0I9GUnPrQhsItr4AAiX/FsS6jeDg092nYSY4JVxmIALNHa7qm2NbWzRYtUTtkJsMT4gffXNWSjAXFEDnZT1ALkmDoows+SpIN0Hv20zzIHz5ENj8jEmyQNoAA0iBiDNqRtUHsABXtu3JMYVctEVB/0MdO4rnu252Jwa3DIwyp0YSM6r4m3X/4xbWB/0Nd4pJ6rZ+xQLhr8JtgZF2Wu2ITSNiw1G1ToMzJ58/T9Ih4doQpCKQW96nl+EE+iqjo3NWLDOU2/xSloluSKh6REO2YhJkmKuX3SmJyOm7DAOWHkxjNmOSwXV3wEFtp9KV0IqLL80StMseb4GyFsBA19zUsGP9DDsg="
notifications:
  slack:
    rooms:
      secure: "ndI32klxt5Kkq1bSlCWrxgeHwYj68xH2RGJX3Q8ccgW3Tp5bGhO2WatRssJPF2URPTNe4GHAaTAeMgg0LsYjtSJ+ULk00j0//3nLTXn/AK+FcAX04BD2A5DXLDIyrwfewlnou58U22aWZ6UBhde425xF3t5MgF7cg8r/Qlg1f2CVCGwbGIW7bkDeGXdCS0OmEPVdb/5xk/GwFQSea7qSbAFyOtIjqqEFYjYN8TKlu/wjc54uppgUXAqqFdLFj9KI6c4y2v1qc98mExPV09B94UomnBKrqCSiaEIxbNgljQuYBHrkxzFXlb2pL0/LyfpYXFxULn0KQEvx9iY9LI9oDJkEhJbncZ4twXlgkeNJEjw6aiwW+SZtBGCIuovv8jSncyXsW3VwvboyIvh3EUXhjTT1dqgIjMU5SA03kJUqvWyJksMAuDf/fKxCbazt/5unjHye4Ny07zLTSoysk36VxvubYrq4VvAl/xVQfIC/nACEUqTWA0LbCY5+KSBQKLARTHfq2QZo6wbQDF4IzyimdeQPtdiGveAZ5UIfxrrYFbmeamDREh4Qv5qyXVCsUPW9Dt58H7koeJYP70iDazQjhbBe5H9wtiSQBzIwqo/7LENKYkFnk8rlJ7YL4rm1QxN6gjgTZU1JZdxPVgdU6mgJVMXZxZ/DKbwPJ/eucrdky28="
