[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.8.12"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.8.12"

[[constraint]]
  name = "github.com/xanzy/go-cloudstack"
  branch = "master"

[[constraint]]
  name = "gopkg.in/gcfg.v1"
  source = "github.com/go-gcfg/gcfg"
  branch = "feature/user_vars"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.8.12"
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.8.12"
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.8.12"
[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

